### ISSUE TITLE
include vendor sass files results empty files.css

### ISSUE THREAD

**Issue by RomainMarecat** [vn38minhtran/generator-gulp-symfony2#1]
I had a problem to include vendors into  `gulp-symfony2.yml`
When i execute `gulp build` all done but i had half empty `vendor.css`
example:
  _bootstrap doesn't exist.

`gulp-symfony2.yml`

```
styles:
  vendor.css:
    - app/Resources/public/vendor/bootstrap-sass/assets/stylesheets/_bootstrap.scss
    - app/Resources/public/vendor/font-awesome/scss/font-awesome.scss
    - app/Resources/public/vendor/slick-carousel/slick/slick.scss
    - app/Resources/public/vendor/slick-carousel/slick/slick-theme.scss
    - app/Resources/public/vendor/flag-icon-css/sass/_flag-icon.scss
    - app/Resources/public/vendor/toastr/toastr.scss
  main.css:
    - app/Resources/public/styles/main.scss

scripts:
  main.js:
    - app/Resources/public/scripts/bar.js
```

`bower.json`

```
{
  "name": "recipe",
  "version": "0.0.1",
  "authors": [
    "Romain Marecat <romain.marecat@gmail.com>"
  ],
  "description": "Vendor assets for the front bundle",
  "license": "MIT",
  "private": true,
  "ignore": [
    "**/.*",
    "node_modules",
    "bower_components",
    "../public/vendor",
    "test",
    "tests"
  ],
  "dependencies": {
    "jquery": "2.*",
    "jquery-ui": "*",
    "slick-carousel": "^1.6.0",
    "flag-icon-css": "*",
    "bootstrap-sass": "*",
    "components-font-awesome": "latest",
    "bootstrap-social": "latest",
    "jquery-focuspoint": "*",
    "toastr": "*",
    "select2": "*",
    "Jcrop": "*",
    "intl-tel-input": "*",
    "simontabor/jquery-toggles": "*",
    "iframe-resizer": "*",
    "hinclude": "*",
    "sweetalert": "*"
  }
}
```

Windows 10 x64
Nginx
Symfony 3.1

```
gulp -v
[11:20:47] CLI version 3.9.1
[11:20:47] Local version 3.9.1
 node -v
v4.5.0
node-sass -v
node-sass       3.10.0  (Wrapper)       [JavaScript]
libsass         3.3.6   (Sass Compiler) [C/C++]
```
